### ISSUE TITLE
Cursor counter works not properly

### ISSUE THREAD

**Issue by artem-schander** [frabert/selection-counter#3]
I like your package, just what I looked for. But there is a small issue; if you select a bunch of strings, it says the number of the selections in the statusbar. Than you hit the arrow button and the same amount of cursors appears in the code but not in the statusbar. For some reason you have to hit the arrow button twice to get the result.

It's not a big problem. I just thought I tell you (in case you didn't noticed)

**Comment by frabert** [comment]
Thanks for reporting this! Unfortunately, I won't be able to look into this issue until September. I will solve this as soon as I can!

**Comment by frabert** [comment]
@Artem-Schander unfortunately I can't reproduce your issue, can you provide a gif to illustrate it better?

**Comment by artem-schander** [comment]
![](http://i.imgur.com/4nbcp92.gif)

**Comment by frabert** [comment]
Could you please try the following?
- Uninstall `selection-counter`
- Close Atom
- Run `apm develop selection-counter`
- Run Atom and test `selection-counter`

**Comment by artem-schander** [comment]
After I followed the steps, Your package is listed under `Development Packages` but I cant use it.
Do I have to activate it or something?

**Comment by frabert** [comment]
You'll probably have to start Atom in development mode then...
View -> Developer -> Open In Dev Mode

**Comment by artem-schander** [comment]
```
Failed to load the selection-counter package
Cannot find module 'underscore-plus'
```

**Comment by frabert** [comment]
Mmm... ok, sorry for making you run through all this :D
Can you try doing `npm install` into the directory of selection-counter and trying again?

**Comment by artem-schander** [comment]
No problem. I like to help the open source community.
The only `selection-counter` folder i could find is located in `/Users/<name>/github/selection-counter`. BTW I'm on OSX. However, I don't think it is the correct folder. `npm-install` has no effect.
I think it should be the `~/.atom/packages` folder ?!

If you want, write me via hangouts or email: https://plus.google.com/+ArtemSchander

**Comment by frabert** [comment]
I'm sorry but I couldn't find your email in your g+ profile :fearful:
Looking at the package.json, it looks like I indeed made a mistake :shit: It should be solved with the last commit. If I understand how `apm develop` works, the `selection-counter` directory should be a git repository. If it is so, that you should try running `git fetch origin` and see if the package works now...

**Comment by artem-schander** [comment]
You're right. `selection-counter` is a git repo, but I thought it should be in another directory.

However, after `git pull` Atom still fails to load underscore.
Here is what i've done + output:

Console:

```
☁  selection-counter [master] git pull origin master
From https://github.com/frabert/selection-counter
 * branch            master     -> FETCH_HEAD
Updating 4705580..27ed4d1
Fast-forward
 package.json | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)
```

```
☁  selection-counter [master] atom --dev
```

Atom:

```
Failed to load the selection-counter package
Cannot find module 'underscore-plus'
Hide Stack Trace
Error: Cannot find module 'underscore-plus'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/tylerdurden/github/selection-counter/lib/selection-counter-view.coffee:1:5)
    at Object.<anonymous> (/Users/tylerdurden/github/selection-counter/lib/selection-counter-view.coffee:1:1)
    at Module._compile (module.js:452:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:347:32)
```

**Comment by frabert** [comment]
You should probably re-run `npm install` on it... Tedious I know :fearful:

**Comment by artem-schander** [comment]
Sorry, my bad :(

The issue is solved.

**Comment by frabert** [comment]
So it correctly shows the number of cursors after you move?

**Comment by artem-schander** [comment]
Yep, just tested. The number of cursors is always correct.

**Comment by frabert** [comment]
Cool :smile: Thanks for your time!
